controller_manager:
  ros_parameters:
    update_rate: 100 # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

  joint_trajectory_controller:
    ros_parameters:
      joints:
        - J1
        - J2
        - J3
        - J4
        - J5
      interface_name: posiiton
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity