controller_manager:
  ros__parameters:
    update_rate: 1000

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    ee_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

forward_position_controller:
  ros__parameters:
    joints:
      - J1
      - J2
      - J3
      - J4
      - J5
      - J6
      # - JLeft
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

arm_controller:
  ros__parameters:
    joints:
      - J1
      - J2
      - J3
      - J4
      - J5
      - J6
    command_interfaces:
      - position
    state_interfaces:
      - position
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    allow_nonzero_velocity_at_trajectory_end: true

ee_controller:
  ros__parameters:
    joints:
      - JLeft
      - JRight
    command_interfaces:
      - position
    state_interfaces:
      - position
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    allow_nonzero_velocity_at_trajectory_end: true

gripper_controller:
  ros__parameters:
    joint: JLeft
    action_monitor_rate: 20.0
    goal_tolerance: 0.0001
    max_effort: 100.0
    allow_stalling: true
    stall_velocity_threshold: 0.0001
    stall_timeout: 2.0
