controller_manager:
  ros__parameters:
    update_rate: 1000

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

forward_position_controller:
  ros__parameters:
    joints:
      - J1
      - J2
      - J3
      - J4
      - J5
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
